name: credit-modelling
services:
  streamlit:
    build: .
    container_name: credit-risk-app
    environment:
      PYTHONPATH: /app
    env_file:
      - .env
    ports:
      - "8503:8501"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8501/_stcore/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    depends_on:
      - minio
      - mlflow
  minio:
    image: minio/minio:latest
    container_name: credit-risk-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports:
      - "9030:9000"
      - "9031:9001"
    volumes:
      - credit_risk_minio_data:/data
    restart: unless-stopped
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    container_name: credit-risk-mlflow
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "5001:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root s3://credit-risk/ --host 0.0.0.0
    depends_on:
      - minio
    restart: unless-stopped
volumes:
  credit_risk_minio_data:
